FROM python:3.12-slim

WORKDIR /app

COPY requirements-mobile.txt .
RUN pip install --no-cache-dir -r requirements-mobile.txt

COPY aprsmon_mobile.py .

EXPOSE 8081

CMD ["python", "aprsmon_mobile.py"]
